# specify base image
FROM node:16-alpine

# switch user from root to node
USER node

# make work directory - to ensure it is created under node user
RUN mkdir -p /home/node/app
# set work directory 
WORKDIR /home/node/app

# download & install a dependencies - use chown to make user the files are oned by node user
COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./

CMD ["npm", "run", "start"]